routes/task_routes.py
from flask import Blueprint, request, render_template, redirect, url_for,flash
from services.task_service import TaskService
from flask_jwt_extended import get_jwt_identity, verify_jwt_in_request
from components.forms import TasksForm
from wtforms.fields import Label
from flask_jwt_extended.exceptions import  (
    NoAuthorizationError,
    InvalidHeaderError,
    JWTDecodeError,
    WrongTokenError,
    RevokedTokenError,
    FreshTokenRequired,
    
)
from functools import wraps


task_routes = Blueprint("task_routes", __name__)

def jwt_required_with_redirect(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        try:
            verify_jwt_in_request()
            return f(*args, **kwargs)
        except NoAuthorizationError:
            flash("Please login to continue", "warning")
            return redirect("/api/v1/auth/login")
        except InvalidHeaderError:
            flash("Invalid authentication header. Please login again.", "warning")
            return redirect("/api/v1/auth/login")
        except JWTDecodeError:
            flash("Invalid token. Please login again.", "warning")
            return redirect("/api/v1/auth/login")
        except WrongTokenError:
            flash("Wrong token type. Please login again.", "warning")
            return redirect("/api/v1/auth/login")
        except RevokedTokenError:
            flash("Token has been revoked. Please login again.", "warning")
            return redirect("/api/v1/auth/login")
        except FreshTokenRequired:
            flash("Fresh login required. Please login again.", "warning")
            return redirect("/api/v1/auth/login")
      
        except Exception as e:
            flash("Authentication error. Please login again.", "warning")
            return redirect("/api/v1/auth/login")
    return decorated_function

@task_routes.route("/add", methods=["POST", "GET"])
@jwt_required_with_redirect 
def add_task():
    current_user_id = get_jwt_identity()
    form = TasksForm()
    if request.method == "GET":
        return render_template("add_tasks.html", form=form)
    else:
        title = form.title.data
        description = form.description.data
        message, status =  TaskService.add_task(title, description,current_user_id)

        if status == 201:
            flash("Task Added Successfully", 'success')
            return redirect(url_for('task_routes.get_tasks'))
        else:
            flash(message, 'danger')


@task_routes.route("/", methods=["GET"])
@jwt_required_with_redirect 
def get_tasks():
    current_user_id = get_jwt_identity()
    service_response, status =  TaskService.get_all_tasks(current_user_id)

    if status == 200:
        return render_template('tasks.html', tasks=service_response)
    else:
        flash(service_response['message'], 'danger')
    


@task_routes.route("/<task_id>", methods=["GET"])
@jwt_required_with_redirect
def get_task(task_id):
    current_user_id = get_jwt_identity()

    task, status =  TaskService.get_task(task_id,current_user_id)
    if status == 200:
        return render_template('task_detail.html', task=task)
    else:
        flash(task["message"], 'danger')
        return redirect(url_for('task_routes.get_tasks'))

@task_routes.route("/<task_id>/edit", methods=["POST", "GET"])
@jwt_required_with_redirect
def update_task(task_id):
    current_user_id = get_jwt_identity()
    task, status = TaskService.get_task(task_id,current_user_id)
    if status != 200:
        flash("Task not found", "danger")
        return redirect(url_for('task_routes.get_tasks'))
    
    form = TasksForm()
    if request.method == 'GET':
        form.title.data = task.get('title')
        form.description.data = task.get('description')
        form.submit.label = Label('submit', 'Edit Task')

        
        return render_template('edit.html', form=form, task=task)

    if form.validate_on_submit():
        title = form.title.data
        description = form.description.data
        message, status = TaskService.update_task(task_id, title, description)
        
        if status == 200:
            flash("Task updated successfully", "success")
            return redirect(url_for('task_routes.get_task', task_id=task_id))
        else:
            flash(message, "danger")
            return render_template('edit.html', form=form, task=task)

    return render_template('edit.html', form=form, task=task)

@task_routes.route("/<task_id>/toggle")
def toggle_task(task_id):
    message, status = TaskService.toggle_task(task_id)
    path = request.args.get('path')
    
    if status == 200:
        if path == 'single':
            return redirect(url_for('task_routes.get_task', task_id=task_id))

        return redirect(url_for('task_routes.get_tasks')) 
    else:
        flash(message, 'danger')
        if path == 'single':
            return redirect(url_for('task_routes.get_task', task_id=task_id))
        return redirect(url_for('task_routes.get_tasks')) 


@task_routes.route("/<task_id>", methods=["POST"])
def delete_task(task_id):    
    message, status =  TaskService.delete_task(task_id)

    if status == 200:
        flash("Task Deleted Successfully", 'success')
    else:
        flash(message, 'danger')
    return redirect(url_for('task_routes.get_tasks'))

templates/add_tasks.html
{% extends 'layout.html' %} {% block side %} {% include 'side.html' %} {%
endblock %} {% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-6 mx-auto">
      <div class="card shadow-sm">
        <div class="card-body">
          <h4 class="card-title text-center text-success fw-bold">
            Add New Task
          </h4>
          <form method="post" action="/api/v1/tasks/add">
            {{ form.csrf_token }}
            <div class="mb-3">
              {{ form.title.label(class="form-label fw-bold") }} {{
              form.title(class="form-control form-control-lg py-0 input-value ",
              placeholder="Enter task title") }} {% if form.title.errors %}
              <div class="text-danger">
                {% for error in form.title.errors %}
                <small>{{ error }}</small>
                {% endfor %}
              </div>
              {% endif %}
            </div>

            <div class="mb-3">
              {{ form.description.label(class="form-label fw-bold") }} {{
              form.description(class="form-control", rows=4 , placeholder="Enter
              task description") }} {% if form.description.errors %}
              <div class="text-danger">
                {% for error in form.description.errors %}
                <small>{{ error }}</small>
                {% endfor %}
              </div>
              {% endif %}
            </div>

            <div class="d-grid">
              {{ form.submit(class="btn btn-primary btn-md") }}
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/edit.html
{% extends 'layout.html' %} {% block side %} {% include 'side.html' %} {%
endblock %} {% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-6 mx-auto">
      <div class="card shadow-sm">
        <div class="card-body">
          <h3 class="card-title text-center text-success fw-bold">Edit Task</h3>
          <form
            method="POST"
            action="{{ url_for('task_routes.update_task', task_id=task.id) }}"
          >
            {{ form.hidden_tag() }}

            <div class="mb-3">
              {{ form.title.label(class="form-label fw-bold") }} {{
              form.title(class="form-control form-control-md",
              placeholder="Enter task title") }} {% if form.title.errors %}
              <div class="text-danger">
                {% for error in form.title.errors %}
                <small>{{ error }}</small>
                {% endfor %}
              </div>
              {% endif %}
            </div>

            <div class="mb-3">
              {{ form.description.label(class="form-label fw-bold") }} {{
              form.description(class="form-control", rows=4, placeholder="Enter
              task description") }} {% if form.description.errors %}
              <div class="text-danger">
                {% for error in form.description.errors %}
                <small>{{ error }}</small>
                {% endfor %}
              </div>
              {% endif %}
            </div>

            <div class="d-grid">
              {{ form.submit(class="btn btn-primary btn-md") }}
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="{{url_for('static', filename='main.css')}}" />
    {%if title%}
    <title>TaskManager - {{title}}</title>
    {%else%}
    <title>TaskManager</title>
    {%endif%}
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
      <div class="container">
        <a class="navbar-brand fw-bold text-primary" href="#">Task Manager</a>
        {% block side %}{% endblock %}
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %}
    <div class="flashed-messages">
      {% for category, message in messages %}
      <div
        class="alert alert-{{ category }} alert-dismissible fade show shadow-sm"
        role="alert"
      >
        {{ message }}
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="alert"
          aria-label="Close"
        ></button>
      </div>
      {% endfor %}
    </div>
    {% endif %} {% endwith %} {% block content %} {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
      integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

templates/login.html
{% extends 'layout.html' %} {% block content %}
<div class="container mt-5">
  <h1 class="fw-bold text-center">Welcome Back!</h1>
  <p class="text-muted text-center mb-4">
    Log in to manage your tasks and boost your productivity.
  </p>
  <div class="card mx-auto shadow-sm" style="max-width: 500px">
    <div class="card-body">
      <h3 class="card-title text-center text-success fw-bold">Login</h3>
      <form method="post" action="">
        {{ form.hidden_tag() }}
        <fieldset>
          <div class="mb-3">
            {{ form.username.label(class="form-label") }} {% if
            form.username.errors %} {{ form.username(class="form-control
            form-control-md is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.username.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.username(class="form-control form-control-md") }}
            {% endif %}
          </div>

          <div class="mb-3">
            {{ form.password.label(class="form-label") }} {% if
            form.password.errors %} {{ form.password(class="form-control
            form-control-md is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.password(class="form-control form-control-md") }}
            {% endif %}
          </div>

          <div class="d-grid">
            {{ form.submit(class="btn btn-primary btn-md") }}
          </div>
        </fieldset>
      </form>

      <div class="text-center pt-3">
        <small class="text-muted">Don't Have An Account?</small>
        <a href="/api/v1/auth/signup" class="text-decoration-none ms-1"
          >Signup</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/side.html
<div class="collapse navbar-collapse" id="navbarNav">
  <ul class="navbar-nav ms-auto">
    <li class="nav-item">
      <a class="nav-link text-dark fw-bold" href="/api/v1/tasks">Tasks</a>
    </li>
    <li class="nav-item">
      <a class="nav-link text-danger fw-bold" href="/api/v1/auth/logout"
        >Logout</a
      >
    </li>
  </ul>
</div>

templates/signup.html
{% extends 'layout.html' %} {% block content %}
<div class="container mt-5">
  <h1 class="fw-bold text-center">Organize Your Life!</h1>
  <p class="text-muted text-center mb-4">
    Sign up to stay on top of your tasks and achieve your goals efficiently.
  </p>
  <div class="card mx-auto shadow-sm" style="max-width: 500px">
    <div class="card-body">
      <h3 class="card-title text-center text-success fw-bold">Signup</h3>
      <form method="post" action="">
        {{ form.hidden_tag() }}
        <fieldset>
          <div class="mb-3">
            {{ form.username.label(class="form-label") }} {% if
            form.username.errors %} {{ form.username(class="form-control
            form-control-md is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.username.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.username(class="form-control form-control-md") }}
            {% endif %}
          </div>

          <div class="mb-3">
            {{ form.password.label(class="form-label") }} {% if
            form.password.errors %} {{ form.password(class="form-control
            form-control-md is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.password(class="form-control form-control-md") }}
            {% endif %}
          </div>

          <div class="mb-3">
            {{ form.confirm_password.label(class="form-label") }} {% if
            form.confirm_password.errors %} {{
            form.confirm_password(class="form-control form-control-md
            is-invalid") }}
            <div class="invalid-feedback">
              {% for error in form.confirm_password.errors %}
              <span>{{ error }}</span>
              {% endfor %}
            </div>
            {% else %} {{ form.confirm_password(class="form-control
            form-control-md") }} {% endif %}
          </div>

          <div class="d-grid">
            {{ form.submit(class="btn btn-primary btn-md") }}
          </div>
        </fieldset>
      </form>

      <div class="text-center pt-3">
        <small class="text-muted">Already Have An Account?</small>
        <a href="/api/v1/auth/login" class="text-decoration-none ms-1">Login</a>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/task_detail.html
{% extends 'layout.html' %} {% block side %} {% include 'side.html' %} {%
endblock %} {% block content %}
<div class="container mt-5">
  <div
    class="card mx-auto shadow-lg border-0"
    style="max-width: 600px; border-radius: 15px"
  >
    <div class="card-body p-4">
      <h3 class="card-title fw-bold text-center text-primary mb-3">
        {{ task.title }}
      </h3>

      <p
        class="card-text text-muted text-center mb-4"
        style="font-size: 1.1rem"
      >
        {{ task.description }}
      </p>

      <hr class="my-4" />

      <div class="d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center">
          <a
            href="/api/v1/tasks/{{ task.id }}/toggle?path=single"
            class="task-toggle"
            style="text-decoration: none"
          >
            <div
              class="checkbox-placeholder {% if task.completed %}checked{% endif %}"
            ></div>
          </a>
          <label
            class="form-check-label fw-bold mb-1"
            for="taskComplete"
            style="cursor: pointer"
          >
            {% if task.completed %} Completed {% else %} Mark as Completed {%
            endif %}
          </label>
        </div>

        <!-- Edit and Delete Actions -->
        <div class="d-flex gap-2">
          <a
            href="/api/v1/tasks/{{ task.id }}/edit"
            class="btn btn-outline-primary btn-sm"
            style="border-radius: 5px; padding: 0.5rem 1rem"
          >
            Edit
          </a>
          <form
            action="/api/v1/tasks/{{ task.id }}"
            method="post"
            style="margin: 0"
          >
            <button
              type="submit"
              class="btn btn-outline-danger btn-sm"
              style="border-radius: 5px; padding: 0.5rem 1rem"
            >
              Delete
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

templates/tasks.html
{% extends 'layout.html' %} {% block side %} {% include 'side.html' %} {%
endblock %} {% block content %}
<div class="container mt-5">
  <div class="row">
    <div class="col-lg-8 mx-auto">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <div></div>
        <a class="btn btn-success btn-sm px-4" href="/api/v1/tasks/add">
          + Add Task
        </a>
      </div>

      <h3 class="mb-2 text-warning">Pending Tasks</h3>
      <div class="card shadow-sm mb-4">
        <div class="card-body">
          {% set pending_tasks = tasks | selectattr('completed', 'equalto',
          False) | list %} {% if pending_tasks %}
          <ul class="list-group">
            {% for task in pending_tasks %}
            <li
              onclick="window.location.href='/api/v1/tasks/{{ task.id }}'"
              style="cursor: pointer"
              class="list-group-item d-flex justify-content-between align-items-center border-0 shadow-sm my-2"
            >
              <div class="d-flex align-items-center">
                <a
                  href="/api/v1/tasks/{{ task.id }}/toggle"
                  class="task-toggle me-2"
                >
                  <div class="checkbox-placeholder"></div>
                </a>
                <a
                  href="/api/v1/tasks/{{ task.id }}"
                  class="text-decoration-none"
                >
                  <label class="form-check-label mb-1 fw-bold text-dark">
                    {{ task.title }}
                  </label>
                </a>
              </div>

              <span class="badge bg-warning text-white">Pending</span>
            </li>
            {% endfor %}
          </ul>
          {% else %}
          <p class="text-center text-muted">No pending tasks available!</p>
          {% endif %}
        </div>
      </div>

      <h3 class="mb-2 text-success">Completed Tasks</h3>
      <div class="card shadow-sm">
        <div class="card-body">
          {% set completed_tasks = tasks | selectattr('completed', 'equalto',
          True) | list %} {% if completed_tasks %}
          <ul class="list-group">
            {% for task in completed_tasks %}
            <li
              onclick="window.location.href='/api/v1/tasks/{{ task.id }}'"
              style="cursor: pointer"
              class="list-group-item d-flex justify-content-between align-items-center border-0 shadow-sm my-2"
            >
              <div class="d-flex align-items-center">
                <a
                  href="/api/v1/tasks/{{ task.id }}/toggle"
                  class="task-toggle me-2"
                >
                  <div class="checkbox-placeholder checked"></div>
                </a>
                <a
                  href="/api/v1/tasks/{{ task.id }}"
                  class="text-decoration-none"
                >
                  <label
                    class="form-check-label mb-1 text-decoration-line-through text-muted"
                  >
                    {{ task.title }}
                  </label>
                </a>
              </div>

              <span class="badge bg-success text-white">Completed</span>
            </li>
            {% endfor %}
          </ul>
          {% else %}
          <p class="text-center text-muted">No completed tasks yet!</p>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}